baseURL = "https://cric96.github.io/"
languageCode = "en-us"
title = "Gianluca Aguzzi"
theme = "hugo-ink"
paginate = 5

copyright = "© Copyright notice"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "A personal website"

	# Optional 64x64 avatar image.
	avatar = "/imgs/me.jpeg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Research"
url = "/research"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3


[[menu.main]]
name = "Posts"
url = "/posts"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/cric96"

[taxonomies]
   tag = "tags"
